### ISSUE TITLE
make project files reference another project file

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#177]
@coloneldork , need elaboration here

**Comment by coloneldork** [comment]
I just want to make one project file kick off another project file so that I don't have duplicate entries in 2 separate projects.

An example: We have the DnD5e project file which has both Darker Dungeons stuff in it and DnD5e. I'd like to make a DarkerDungeion project file that creates the token and macro sets and then executes the DnD5e project file to make its stuff too. We could then make a 3rd file that includes Trey's logtMT stuff that references those files.

I would consider it extra credit if I could create one Log4MT project that could reference both of those other projects and possible control which ones were created from the command line. But, this is just for developers so I expect them to know WTF they are doing. Ish

**Comment by mr-ice** [comment]
What I would tend to do is use the makefile to link projects, but I think it won't be a problem to do something like this:

```
<project>
    [...]
    <project name="FromHere"/>
    <project name="ToThere"/>
</project>
```

**Comment by coloneldork** [comment]
This is exactly what I would like it to do

**Comment by mr-ice** [comment]
This is closed in the dev-164 branch, coming soon to a master branch near you.
