### ISSUE TITLE
Build all macros into the token library

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#272]
Rtfs

**Comment by mr-ice** [comment]
Build all macros from the extracted token directory into the token when assembling.

1. Currently a macro placeholder tag is left to tell us which ones to load when assembling.  Should we whack the entire macroPropertiesMap when loading from the filesystem?
2. Do we need to preserve any macros that are still on the token? (or added there)  This requires that we know the index values of those to not repeat them.  Otherwise we can just increment starting at 1.    And should we need to preserve them we would invalidate item 1.


So, simplest would be to drop the macroPropertiesMap on token extraction, and on token assembly find all the .command files and add them, rebuilding the index.  This would require rewriting the <index> in the macro to the <int> in the map container.

**Comment by trey-kirk-sp** [comment]
Macros in the file system should be considered authoritative, which I believe is what your last comment drives towards. I would also contend that you want to find all the .xml files. It stands to reason a Macro may have 0 or 1 Command, but must have exactly 1 XML definition. Otherwise you have several things to infer or assume if you try to include a .command with no corresponding .xml.

**Comment by mr-ice** [comment]
pulling out &lt;index&gt; from the macros will keep us from putting unused/unnecessary .

However, I'm also seeing the &lt;label&gt; with the git tag making it into the extracted files.
