### ISSUE TITLE
Error during setup monster token

### ISSUE THREAD

**Issue by havoclad** [mr-ice/maptool-macros#280]
Steps to reproduce
1) setup monster token
2) accept search (assume you found something)
3) select "Roll Hit Points"
4) on bonusHP dialog select "cancel"

Receive error message in chat

Unresolved value "BonusHP".
Error trace : o5e_Token_Monster_applyProperties@Lib:Open5e <<< o5e_Token_applyMonsterToon@Lib:Open5e <<< o5e_Macro_setupToken@Lib:Open5e <<< Setup Monster Token@gm

**Comment by havoclad** [comment]
Attached Glabrezu token, this also happened with Skeltons and wights.  I haven't tested further.
[Glabrezu.rptok.zip](https://github.com/mr-ice/maptool-macros/files/6281189/Glabrezu.rptok.zip)

**Comment by trey-kirk-sp** [comment]
@havoclad do you have a campaign property named "BonusHP"? If not, you may need to update campaign properties. It was added just over two weeks ago: https://github.com/mr-ice/maptool-macros/pull/257

**Comment by trey-kirk-sp** [comment]
After correcting campaign properties, encountered a new error:
```
Error executing "setBarVisible": there is no impersonated token.
Error trace : dnd5e_applyHealth@Lib:DnD5e <<< o5e_Token_applyMonsterToon@Lib:Open5e <<< o5e_Macro_resetToken@Lib:Open5e <<< Reset Monster Token@gm
```

No apparent reason for this to happen, especially since applyMonsterToon has already switched to the token context:
```
[h: monsterToon = arg(0)]
[h: tokenId = arg(1)]
[h: switchToken (tokenId)]
...
[h: params = json.set("{}", "id", currentToken(), "current", HP, 
	"temporary", TempHP, "maximum", MaxHP,
	"dsPass", 0, "dsFail", 0, "exhaustion6", 0,
	"text-type", "o5e", "text-value", "")]
[h, macro("dnd5e_applyHealth@Lib:DnD5e"): params]
```
Recently, dnd5e_applyHealth was set to autoexec=false. Doesn't seem like a reason why this would change the context which that macro runs. But I changed it from the classic style to UDF and that helped:

```
[h: params = json.set("{}", "id", currentToken(), "current", HP, 
	"temporary", TempHP, "maximum", MaxHP,
	"dsPass", 0, "dsFail", 0, "exhaustion6", 0,
	"text-type", "o5e", "text-value", "")]
[h: dnd5e_applyHealth (params)]
```

So I guess we'll just do that instead.


Macros are dumb.
