### ISSUE TITLE
Create a dialog to allow HP to be updated in MapTool

### ISSUE THREAD

**Issue by coloneldork** [mr-ice/maptool-macros#45]
Currently the only way to track hit points is doing it in DnDBeyond and running the Quick Update macro. There needs to be a local HP update macro to handle this so a player doesn't need to go back and forth between DnDBeyond if they don't want to do that.

**Comment by trey-kirk-sp** [comment]
The problem is  this doesn't prevent the user from still having to visit DnDBeyond anyways, at least not if there's anything else they need to change. Even then, they won't want to refresh until they've updated DnDB with their total HP changes. So while this is still probably a worth-while endeavor, as it would be a useful macro in the core DnD5e campaign, I don't see it doing much to prevent folks from having to revisit DnDB.

**Comment by trey-kirk-sp** [comment]
Pretty sure this is done.
