### ISSUE TITLE
Lib-DNDBeyond - Migrate campaign macros

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#46]
To install the macros, the user has to initiate a build command that requires the user to know exactly what macros to include in the macro set. This is undesirable. When a campaign macro is updated, the user has to delete the old one and import the new one. This is a PITA. To avoid all of that, we should model the campaign macros just like the player macros: keep their source macro on the token library and place a wrapper on the macro panel that they are best suited.

Tasks:
- Move the campaign macros to a new group under Lib:DnDBeyond
- Update Campaign Init to create wrappers for these macros on the Campaign panel
- Update Lib-DnDBeyond/Readme.md to reflect the macro set is no longer a required build artifact
Note: With Quick Update having migrated to being a token macro, this is a good time for it to quietly stop showing up on the campaign panel, as well.

**Comment by mr-ice** [comment]
Point of order.

One only has to "know" the macro set right now because the tools under development are still primitive.  A future state would understand what you needed from the macroset -- but that requires that we be able to record that somewhere.  That recording is being done today in the README under Lib-DNDBeyond, but could easily be done as a script, as a make target, as a shell alias, as a entrypoint in a new Dockerfile, etc.

The direction we want to take, though is to create a .project file with a description of everything you need, including the names of macros to build into a macset.

All that being said, I really like the idea of dropping the token on and pushing the campaign init button to have the campaign panel populated.

**Comment by trey-kirk-sp** [comment]
Also a good time to reorganize the token macros. Where each general macro would allow the player to create a personal macro (Attacks, Skills, Saves & Spells), those personal macros are sorted away in a different group than the original macro that created them. I think it makes much more sense for the generic macros to live in that same macro group thus keeping all the macros that attack together, that cast spells together, etc.

It would initially look like:
![image](https://user-images.githubusercontent.com/6287933/86060749-034d9e80-ba2b-11ea-8e72-d1f1bf858eef.png)

After some use, it might look something like:

![image](https://user-images.githubusercontent.com/6287933/86060686-e022ef00-ba2a-11ea-8207-585bd26259d9.png)

Points of emphasis:
- All personal macros should get some sort of sort prefix (usually based on the selected item); The generic macro's sort order should remain blank, guaranteeing it will always bubble up to the front of the list.
- If not done yet, make Cast Spell a player editable macro
- Convert any macro not yet using it to roll using dndb_DiceRoller_roll
- The uber-generic "Make Check" macro has likely outlived its usefulness

**Comment by trey-kirk-sp** [comment]
28 days later, the project-assemble has removed much of the pain this was going to address. So instead, I'll pivot from there and:

- [ ] Implement Jay's latest pattern using for adv/disadv on the all player macros; implement a preference for his current label or &and;/&or;
- [ ] Make Spells player editable.
- [ ] Reorg the player macros into their own groups.
