### ISSUE TITLE
Build: separate structure from content

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#5]
I'll expand more in this when I'm not on a phone, but the jist is this: one or more macro sources are encapsuled in a single XML file. I expect that file can be first sanitized of client-relevant details. I also would like to extract macro sources from these sanitized XML files and replace them with placeholders. The macro sources would persist in a separate file where changes are more easily represented in Git. The build would have to reconstruct the XML before building the MT artifact. I wonder if an XSLT solution would help.

**Comment by mr-ice** [comment]
XSLT could help, but it's just the 'content' attribute that needs to be extracted, unless you want to manipulate any of the other attributes.

Putting it back looks equally just as easy as putting the "content" string back in the "content" attribute with some xml encoding.  The only thing that has to be done special is encoding a few special characters.    Doing this is bash is not ideal, so we would need to choose perhaps another language.  Python would be my first choice, after that it's pretty wide open except Perl will have to stay in the closet where it belongs, it knows what it did.

I'd also like to explore the list and campaign formats which are collections of things to ensure we can build those if needed from anything else.

then assembly may be

content -> xml properties -> list -> campaign 

after that we can start getting fancy

**Comment by trey-kirk-sp** [comment]
re: xml encoding: Screw that noise. Wrap the command source in <![CDATA[  ]]> and no XML encoding would be required.

**Comment by mr-ice** [comment]
Well, we could do what you're saying, or we could do what the tool that we're hoping to be compatible with is doing.  We're going to have to deal with it coming out of maptool anyway, but the nice thing is that I think the tool frameworks are going to handle it automatically.

**Comment by mr-ice** [comment]
TODO: still need to fully separate the artifacts, and of course the build has to put them back together.

maptool artifacts (MA) are tokens, properties, macros, and macro sets (seen thus far).  For the purposes of this project we are most interested in 

net.rptools.maptool.model.MacroButtonProperties

which have a command property which is the subject we are hoping to track/develop/share here.

The build should take care of deconstruction of the MA parts that represents the MA (since the MA is almost always a zip archive of two common files and a few uncommon ones (only content.xml seems to contain net.rptools.maptool.model.MacroButtonProperties).

the content.xml describes the thing that was the MA with its root level item

| MA | content.xml root |
| --- | ---------------- |
| mtmacro | net.rptools.maptool.model.MacroButtonProperties |
| mtmacset | list |
| rptok | net.rptools.maptool.model.Token |
| mtprops | net.rptools.maptool.model.CampaignProperties |

All of the net.rptools.maptool.model.MacroButtonProperties should become their own first order object in this library, and inclusion of those into MAs should be able to be done with full flexibility.  I think this means there will need to be a unique name for each, and a place to find them in the hierarchy, and a way to include them into any MA type without having to copy them around.

We'll still need to save or synthesize the rest of the MA for reconstruction.  And we will need a thing that each MA will use to refer to the list of net.rptools.maptool.model.MacroButtonProperties that are wanted.  They shouldn't be required to go back only to the same thing from which they came.  I think this means we'll need a schema for each MA and perhaps a project specific way to include net.rptools.maptool.model.MacroButtonProperties into an object being built.

Probably one or more of:

- commandline
- manifest file
- directory hierarchy

**Comment by mr-ice** [comment]
When building the 'xc' (eXtract Command) utility, I noticed the label or name of a macro was not restricted from having some uncomfortable characters in the name.

leading spaces
spaces
slashes

These make them a little harder to deal with when extracting them to the filesystem.  Certain characters would be a problem for our shell and other tools to interact with the files on the filesystem. So for the purposes of the examples seen thus far a simple url encoder was used to obfuscate those characters -- this needs to be codified so that when reconstructing we know what we're trying to include.  

For example a filesystem based linking strategy would have to use the encoded name to refer to the macro, instead of the label name.


- macro name is the net.rptools.maptool.model.MacroButtonProperties label property
- library name for the macro has to be a library friendly name -- at least not including shell and filesystem special and reserved characters.

**Comment by trey-kirk-sp** [comment]
I think the breaking it out part is certainly nice, but for me it was more important to build it all back together. If the focus were to just assemble, it simplifies the structure because we could implement the content.xml file with directives to the file sources that are arbitrarily named.

**Comment by trey-kirk-sp** [comment]
See recent commit that illustrates what I mean.

**Comment by mr-ice** [comment]
almost arbitrarily named

I think we're on the same track, just had to figure out how to break it apart before figuring out how to reconstruct it.  For example, I'm pretty sure now that I can reconstruct a mtmacro from a command.txt and content.xml.   I'm pretty sure I can reconstruct a mtmacset from any number of mtmacro files.

The rptok is a tiny bit more interesting as it's not the same as a mtmacset embedded in the rptok.  And I haven't really started pulling apart the campaign properties.

But, replacing net.rptools.maptool.model.MacroButtonProperties with a placeholder like
<net.rptools.maptool.model.MacroButtonProperties ref="externalname"></net.rptools.maptool.model.MacroButtonProperties> ought to let us quickly rehydrate the macros into that spot when rebuilding the maptool asset.

**Comment by mr-ice** [comment]
I see your example, let me show you a counter example.

**Comment by mr-ice** [comment]
hrm... not sure how you put that branch on this issue

**Comment by trey-kirk-sp** [comment]
commit comment begins with "Issue #5 - blah"

**Comment by mr-ice** [comment]
I'll do an example reconstruction on that branch, but basically if we're rebuilding AttackMacros, we'll find an empty macro with a src attribute, we'll open that directory[1], put the command.txt into the command attribute of content.xml, and then plug that entire thing into where we found the empty macro, replacing it.

[1] relative to our library

**Comment by trey-kirk-sp** [comment]
So in the same pattern, the Lib-DNDBeyond token, which currently has 28 macros, would have 28 directories w/ command.txt in each?

**Comment by trey-kirk-sp** [comment]
I'm not thrilled with invalidating the validity of the original XML with a custom property, but I'm pretty sure I can quickly get over that. But I'm feeling more opposed to a whole bunch of directories holding a single file. I guess the idea is that the property indicates the directory while the filename indicates the element content? Could we consider a property value that indicates that instead?
Ala.
src = "command:src/macroFileName.txt"

**Comment by trey-kirk-sp** [comment]
bad commit comment, bad!

**Comment by mr-ice** [comment]
neat!

the new micro-assemble demonstrates reassembly from the format I'm suggesting.

Working on a macro-assemble now that will actually pick up information from the files themselves.

**Comment by mr-ice** [comment]
well, crap, forgot #5 again.

dockerrun macro-assemble macro/Single

Will create the .mtmacro from macro/Single.xml and macro/Single.command

you can specify macro/Single macro/Single.xml or macro/Single.command and they will all work the same

**Comment by trey-kirk-sp** [comment]
Is this currently in Master? I ask cuz I'm having disagreeing results:


```
trey.kirk@tkirk-11913  /c/GITRoot/maptool-macros (tkirk/docker-cmdScripts)
$ git status
On branch tkirk/docker-cmdScripts
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        out.txt

nothing added to commit but untracked files present (use "git add" to track)

trey.kirk@tkirk-11913  /c/GITRoot/maptool-macros (tkirk/docker-cmdScripts)
$ git pull origin master
From github.com:mr-ice/maptool-macros
 * branch            master     -> FETCH_HEAD
Already up to date.

trey.kirk@tkirk-11913  /c/GITRoot/maptool-macros (tkirk/docker-cmdScripts)
$ ./dockerrun macro-assemble macro/Single
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"macro-assemble\": executable file not found in $PATH": unknown.

```

**Comment by mr-ice** [comment]
It is, did you ./dockerbuild since you pulled?

**Comment by trey-kirk-sp** [comment]
didn't. now did. we good.

**Comment by mr-ice** [comment]
created a PR for a partial solution, working on the next bit (re-creating rptok from parts).

https://github.com/mr-ice/maptool-macros/pull/19

Eventually I'll remember to put the #5 on my commit message

**Comment by mr-ice** [comment]
Ok, now there exist a token-assemble and token-extract to do the needful.

I tested it trivially by extracting, the re-creating the rptok and comparing the two if I just extracted them via zip.

There are differences in the escaping.   It looks like maptools escapes &quot; when exporting, but that's not strictly necessary and I haven't figure out how to get the xml parser I'm using to do it the same way.  The token imports correctly and the macro appears intact comparing the screen to the file.

So, I'm declaring a partial win.

**Comment by mr-ice** [comment]
make sure to dockerbuild

**Comment by mr-ice** [comment]
@trey-kirk-sp  found that the macro-extract and token-extract quoted spaces differently, so I'm going to consolidate those to make them the same.  While doing that I'll change the quoting to use '+' instead of %20 for spaces.

**Comment by mr-ice** [comment]
structure and content separated.
